CREATE TABLE CONGVIEC (
    MADA int,
    STT int,
    TEN_CONG_VIEC nvarchar(50),
)

CREATE TABLE PHANCONG (
    MA_NVIEN char(9),
    MADA int,
    STT int FOREIGN KEY (),
    THOIGIAN float,
)

CREATE TABLE DEAN (
    MADA int,
    TENDA NVARCHAR(15),
    DDIEM_DA NVARCHAR(15),
    PHONG int,
)

CREATE TABLE PHONGBAN (
    MAPHG int,
    TENPHG NVARCHAR(15),
    TRPHG CHAR(9),
    NG_NHANCHUC DATE,
)

CREATE TABLE NHANVIEN (
    MANV char(9),
    HONV NVARCHAR(15),
    TENLOT NVARCHAR(15),
    TENNV NVARCHAR(15),
    NGSINH DATE,
    DCHI NVARCHAR(30),
    PHAI NVARCHAR(3),
    LUONG FLOAT,
    MA_NQL CHAR(9),
    PHG int,
)

CREATE TABLE DIADIEM_PHG (
    MAPHG int,
    DIADIEM NVARCHAR(15),
)

CREATE TABLE THANNHAN (
    MA_NVIEN CHAR(9),
    TENTN NVARCHAR(15),
    PHAI NVARCHAR(3),
    NGSINH DATE,
    QUANHE NVARCHAR(15),
)